language: node_js
group: edge
sudo: required
services:
  - mongodb
  - docker
node_js:
  - "4.4.3"
  - "6.9.1"
before_install:
  - npm install fh-build@git://github.com/sedroche/fh-build.git#7476751f8157fe92625467b52ab11deab784b8e7 -g
  - fh-build template
install: npm install
